name: mermaidstudio

services:
  web:
    container_name: mermaidstudio
    image: mermaidstudio:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "3000:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/index.html"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: unless-stopped
